site_name: KTech Knowledgebase
site_url: https://example.com/
nav:
  - Home: index.md
  - 3D Modeling:
      - Blender: design/blender.md
      - Fusion 360: design/fusion_360.md
  - Additive Manufacturing:
      - 3D Printing: additive_manufacturing/3d_printing.md
  - Coding:
      - .Net: coding/dotnet.md
      - Electron: coding/electron.md
      - GitHub: coding/github.md
      - Python: coding/python.md
  - Cloud:
      - Azure: cloud/azure.md
  - Game Development:
      - Unity 3D: game_dev/unity.md
      - Unreal Engine: game_dev/unreal.md
  - Graphic Design:
      - Photoshop: graphic_design/photoshop.md
  - Health:
      - Recipes: health/recipes.md
  - Microcontrollers:
      - Arduino: microcontrollers/arduino.md
      - Raspberry Pi: microcontrollers/raspberry_pi.md
  - System Administration:
      - Powershell: sysadmin/powershell.md
theme: readthedocs
extra_css: [extra.css]
